global:
  scrape_interval: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #  external_labels:
  #    monitor: 'codelab-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093 #default alert manager port is 9093

rule_files:
  - "/rules/*.rules.yml"

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 30s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sql'

    scrape_interval: 30s

    static_configs:
      - targets: ['sql-exporter:9399']